# Generated by Django 2.1.9 on 2020-03-04 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('has_water', models.BooleanField(default=False)),
                ('has_atmosphere', models.BooleanField(default=False)),
                ('order_from_star', models.IntegerField()),
                ('distance_from_star', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('star_type', models.CharField(choices=[('M', 'Red star'), ('G', 'Yellow star')], default='G', max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='planet',
            name='star',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planets', to='starsystem.Star'),
        ),
    ]
