# Generated by Django 2.1.9 on 2020-09-17 11:45

from django.db import migrations

def fix_planets(apps, schema_editor):
    Planets = apps.get_model('starsystem', 'Planet')
    for planet in Planets.objects.all():
        planet.has_atmosphere = False
        planet.save()

class Migration(migrations.Migration):

    dependencies = [
        ('starsystem', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fix_planets),
    ]
